name: Azure Static Web Apps CI/CDname: Azure Static Web Apps CI/CD



on:on:

  push:  push:

    branches:    branches:

      - main      - main

  pull_request:  pull_request:

    types: [opened, synchronize, reopened, closed]    types: [opened, synchronize, reopened, closed]

    branches:    branches:

      - main      - main



jobs:jobs:

  build_and_deploy_job:  build_and_deploy_job:

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    name: Build and Deploy Job    name: Build and Deploy Job

    steps:    steps:

      - uses: actions/checkout@v3      - uses: actions/checkout@v3

        with:        with:

          submodules: true          submodules: true

          lfs: false          lfs: false

      - name: Build And Deploy      - name: Build And Deploy

        id: builddeploy        id: builddeploy

        uses: Azure/static-web-apps-deploy@v1        uses: Azure/static-web-apps-deploy@v1

        with:        with:

          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_OCEAN_0FBA3420F }}

          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)

          action: "upload"          action: "upload"

          skip_deploy_on_missing_secrets: true          skip_deploy_on_missing_secrets: true

          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######

          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig

          app_location: "/" # App source code path          app_location: "/" # App source code path

          api_location: "" # Api source code path - optional          api_location: "" # Api source code path - optional

          output_location: "build" # Built app content directory - optional          output_location: "build" # Built app content directory - optional

          app_build_command: "npm run build" # Custom build command          app_build_command: "npm run build" # Custom build command

          ###### End of Repository/Build Configurations ######          ###### End of Repository/Build Configurations ######



  close_pull_request_job:  close_pull_request_job:

    if: github.event_name == 'pull_request' && github.event.action == 'closed'    if: github.event_name == 'pull_request' && github.event.action == 'closed'

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    name: Close Pull Request Job    name: Close Pull Request Job

    steps:    steps:

      - name: Close Pull Request      - name: Close Pull Request

        id: closepullrequest        id: closepullrequest

        uses: Azure/static-web-apps-deploy@v1        uses: Azure/static-web-apps-deploy@v1

        with:        with:

          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_OCEAN_0FBA3420F }}

          action: "close"          action: "close"
